### ISSUE TITLE
作者你只是机械复制了Py的实现

### ISSUE THREAD

**Issue by ComradeFu** [iopass4/behavior3-lua#1]
深入的机制我并没有看到有所体现，很可惜。
部分代码不是lua的最优习惯写法，希望多注意一下。

**Comment by iopass4** [comment]
嗯 嗯 这个只是第一版，把功能实现出来 .. 

基本的功能都在这里了 .

求多多指点呀~

**Comment by ComradeFu** [comment]
先实现出来也对，不过还不够，真的不够。

我最近也在纠结，纠结节点维护的问题（重点是running状态的维护），所以才git上面找找看。这个原作者实现得很好，但是有几个地方我一直觉得是bug，无奈他也不回复我的询问。

你注释掉的地方，就是他实现的最重要的地方，不知你们的进度如何，我们一起探讨探讨吧。

**Comment by iopass4** [comment]
好啊 讨论下呀~ 是哪个我注释掉的?

 我用着还不错啊~

**Comment by ComradeFu** [comment]
open_nodes 的维护，在BTree以及tick那里。

**Comment by iopass4** [comment]
openNodes 的维护 在tick里面用 _enterNode 和 _closeNode 里呀 ..你看看，注释掉的是不写在那里维护了，我上传的时候忘记删了~~

**Comment by panni1843** [comment]
请问他的并行是怎么实现的？还是要自己写？

**Comment by iopass4** [comment]
并行 看看 Sequence ~
